teste/Models/ErrorViewModel.cs
namespace teste.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

teste/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace teste.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        
    }
}

teste/Models/UsuarioDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace teste.Models
{
    public class UsuarioDbContext : DbContext
    {
        public UsuarioDbContext(DbContextOptions<UsuarioDbContext> options)
        : base(options){

        }

        public DbSet<Usuario> Usuarios{get; set;}

        protected override void OnModelCreating(ModelBuilder modelBuilder){
            var usuario = modelBuilder.Entity<Usuario>();
            usuario.ToTable("usuario");
            usuario.HasKey(x => x.Id);
            usuario.Property(x => x.Id).HasColumnName("id").ValueGeneratedOnAdd();
            usuario.Property(x => x.Nome).HasColumnName("nome").IsRequired();
            usuario.Property(x => x.Email).HasColumnName("email");
            usuario.Property(x => x.Senha).HasColumnName("senha");


        }
    }
}

teste/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using teste.Models;

namespace teste.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Usuarios()
    {
        return View(usuarios);
    }

    private static IList<Usuario> usuarios =
    new List<Usuario>(){
        new Usuario(){
            Id = 1,
            Nome = "Roberta Teles",
            Email = "roberta@email.com",
            Senha = "12345678"
        },
        new Usuario(){
            Id = 2,
            Nome = "Marcia Guimaraes",
            Email = "marcia@email.com",
            Senha = "12345678"
        },
        new Usuario(){
            Id = 3,
            Nome = "Lindemberg Teles",
            Email = "berg@email.com",
            Senha = "12345678"
        },
        new Usuario(){
            Id = 4,
            Nome = "Bruna Lins",
            Email = "bruna@email.com",
            Senha = "12345678"
        }
    };

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

teste/Controllers/HomeEFController.cs
using Microsoft.AspNetCore.Mvc;
using teste.Models;

namespace teste.Controllers
{
    public class HomeEFController : Controller
    {
        private UsuarioDbContext _context;
        
        public HomeEFController(UsuarioDbContext context){
            _context = context;
        }

        public IActionResult Index(){
            var usuario = _context.Usuarios.ToList();
            return View(usuario);
        }

        public IActionResult Create(){
            return View();
        }

        [HttpPost]
        public IActionResult Create(Usuario usuario){
            _context.Add(usuario);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id){
            if(id == null){
                return NotFound("Id não encontrado");
            }

            var usuario = _context.Usuarios.SingleOrDefault(a => a.Id == id);

            if(usuario == null){
                return NotFound("Usuário não encontrado.");
            }

            return View(usuario);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteUser(int id){
            var usuario = _context.Usuarios.SingleOrDefault(a => a.Id == id);
            if(usuario == null){
                return NotFound("Usuário não encontrado");
            }
            _context.Usuarios.Remove(usuario);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id){
            if(id == null){
                return NotFound("Id não encontrado");
            }

            var usuario = _context.Usuarios.SingleOrDefault(a => a.Id == id);

            if(usuario == null){
                return NotFound("Usuário não encontrado.");
            }

            return View(usuario);
        }

        [HttpPost]
        public IActionResult Edit(int id, Usuario usuario){
            if(id != usuario.Id){
                return NotFound("Id não encontrado");
            }
            if(ModelState.IsValid){
                _context.Update(usuario);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }
    }
}

teste/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using teste.Models;
using teste.Repository;

namespace teste.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class UserController : ControllerBase
    {
        private readonly IUsuarioRepository _repository;

        public UserController(IUsuarioRepository repository){
            _repository = repository;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll(){
            var usuarios = await _repository.GetUsuarios();
            return usuarios.Any() ? Ok(usuarios) : NoContent();
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(int id){
            var usuario = await _repository.GetUsuarioById(id);
            return usuario != null
            ? Ok(usuario) : NotFound("Usuário não encontrado");
        }

        [HttpPost]
        public async Task<IActionResult> Save(Usuario usuario){
            _repository.AddUsuario(usuario);
            return await _repository.SaveChangeAsync()
             ? Ok("Usuário cadastrado") : BadRequest("Algo deu errado");
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(int id, Usuario usuario){
            var usuarioExiste = await _repository.GetUsuarioById(id);
            if(usuarioExiste == null) return NotFound("Usuário não encontrado.");

            usuarioExiste.Nome = usuario.Nome ?? usuarioExiste.Nome;
            usuarioExiste.Email = usuario.Email ?? usuarioExiste.Email;
            usuarioExiste.Senha = usuario.Senha ?? usuarioExiste.Senha;

            _repository.AtualizarUsuario(usuarioExiste);

            return await _repository.SaveChangeAsync()
            ? Ok("Usuário atualizado.") : BadRequest("Algo deu errado. Tente novamente!");
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id){
            var usuarioExiste = await _repository.GetUsuarioById(id);
            if(usuarioExiste == null) return NotFound("Usuário não encontrado.");

            _repository.DeletarUsuario(usuarioExiste);

            return await _repository.SaveChangeAsync()
            ? Ok("Usuário deletado.") : BadRequest("Algo deu errado. Tente novamente!");
        }
    }
}

teste/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Viagens de ônibus e avião mais baratas</h1>
    <p>Volte a sonhar com a sua próxima viagem. Encontre reservas flexíveis e os melhores preços para voos e pacotes.</p>
</div>

teste/Views/Home/Usuarios.cshtml
@model IEnumerable<teste.Models.Usuario>
@{
    ViewData["Title"] = "Nossos Usuarios";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
        </tr>
    }
    <tbody>
</table>

teste/Views/HomeEF/Create.cshtml
@model teste.Models.Usuario
@{
    ViewData["Title"] = "Adicionar";
}

<h1>Adicionar novo user</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control"/>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" type="password" class="form-control"/>
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary"/>
            </div>      
        </form>
    </div>
</div>
<div>
    <a asp-action="Index"> Voltar para a lista</a>
</div>

teste/Views/HomeEF/Delete.cshtml
@model teste.Models.Usuario
@{
    ViewData["Title"] = "Deletar";
}

<h1>Deletar</h1>
<h3>Tem certezar em excluir o usuário</h3>
<div>
    <h4>Usuário</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Excluir" class="btn btn-danger"/>
        |
        <a asp-action="Index"> Voltar para Lista</a>
    </form>
</div>

teste/Views/HomeEF/Edit.cshtml
@model teste.Models.Usuario
@{
    ViewData["Title"] = "Adicionar";
}
<h1>Atualizar usuario</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control"/>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" type="password" class="form-control"/>
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-primary"/>
            </div>      
        </form>
    </div>
</div>
<div>
    <a asp-action="Index"> Voltar para a lista</a>
</div>

teste/Views/HomeEF/Index.cshtml
@model IEnumerable<teste.Models.Usuario>
@{
    ViewData["Title"] = "Nossos Usuarios";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th> <a asp-action="Create">Adicionar</a></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
            </td>
        </tr>
    }
    <tbody>
</table>

teste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TravelAirlines</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/teste.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TravelAirlines</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HomeEF" asp-action="Index">Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - teste - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>